### ISSUE TITLE
Set up Etherspot SDK

### ISSUE THREAD

**Issue by paigel** [rmx-party/hacks#1]
- [ ] get pop-up working

**Comment by brandondees** [comment]
https://docs.etherspot.io/getting-started/install-sdk

**Comment by brandondees** [comment]
lots of snags so far, between outdated docs, mismatched dependency versions, bundler configuration gotchas, etc.

astro seems like a great framework choice still but there are some nuances to how modules and client side inline scripts interact that i don't think i should take the time to learn about right now.

i moved on to vite's react starter template which seems relatively straightforward but there were some client-server globals / stdlib config gotchas there too, that sucked up a bunch of time today before i could get to `console.log(web3auth)` - now i'm still working on web3 auth modal setup stuff, there are probably some details i've missed in the docs and need to go back through setting up the network configs etc

**Comment by paigel** [comment]
blocked by #9: Need to first recombine the codebases first to revisit setting up SDK

**Comment by brandondees** [comment]
this is technically done but only the prerequisite steps to proceed with other tasks
