### ISSUE TITLE
[Function] After login, user should see their account info

### ISSUE THREAD

**Issue by paigel** [rmx-party/hacks#12]
# Criteria
```
After login, user should see their account info. They should see the minimal information possible to mint:
* balance
* wallet address
* message that informs user they need funds to mint
```

Note: Some of this might be built-in with magic. Will confirm once implemented and pair with a designer to complete.

## Tasks
~~- [ ] once prototype for this works, pair with a designer to confirm UI~~
- [x] show balance
- [x] show wallet address
- [x] show messaging

**Comment by brandondees** [comment]
this is still pretty janky but works if you load the page when already logged in.

**Comment by brandondees** [comment]
the pre-mint UI is ready for design pair, minting will be broken until we get the smart contract deployed to mumbai

**Comment by paigel** [comment]
will extract the UI tasks from this one and make a separate ticket
