### ISSUE TITLE
Write NFT Contract

### ISSUE THREAD

**Issue by paigel** [rmx-party/hacks#3]
Write and deploy smart contract

---

# Metadata

### 0. Global Content
- [x]  RMX ASCII
[RMX - ASCII.txt](https://github.com/rmx-party/hacks/files/11458216/RMX.-.ASCII.txt)

### NFT 1. Hello, World!
- [x]  SVG
```
<svg width="800" height="800" xmlns="http://www.w3.org/2000/svg">
 <style>svg{background-color: white; font-family: monospace;}</style>
 <g>
  <text font-size="64" id="svg_1" y="128" x="64" stroke-width="0" stroke="black" fill="black">Hello, World!</text>
 </g>

</svg>
```
- [x] Name: Hello, World! (no number)
- [x]  Description: (same for all)
```
The first experiment of our RMXhacks series. Powered by ERC-4337, mint two separate NFTs with one click — no wallet needed, no signature needed. We’re testing for usability, without the frills (pizza bagel included).
```
- [x]  Variables or traits: none

### 2. Pizza, Bagel!
- [x]  SVG
```
<svg width="800" height="800" xmlns="http://www.w3.org/2000/svg">
 <style>svg{background-color: blue; font-family: cursive;}</style>
 <g>
  <text font-size="80" id="svg_1" y="128" x="64" stroke-width="0" stroke="#00ff00" fill="#00ff00">Pizza, Bagel!</text>
 </g>

</svg>
```
- [x] Name: Pizza, Bagel! (no number)
- [x]  Description: (same for all)
```
The first experiment of our RMXhacks series. Powered by ERC-4337, mint two separate NFTs with one click — no wallet needed, no signature needed. We’re testing for usability, without the frills (pizza bagel included).
```
- [x]  Variables or traits: none

### **OpenSea Metadata**

- [x]  Collection Name: **RMXhacks—001**
- [x]  Description
```
The first experiment of our RMXhacks series. Powered by ERC-4337, mint two separate NFTs with one click — no wallet needed, no signature needed. We’re testing for usability, without the frills (pizza bagel included).

Read more about RMXhacks here: [https://mirror.xyz/rmxparty.eth/bSbFlMzy7X7NNW11tLc-HYWeMt6NvReTDVTQUkI_UcQ](https://mirror.xyz/rmxparty.eth/bSbFlMzy7X7NNW11tLc-HYWeMt6NvReTDVTQUkI_UcQ)
```
- [x] Image: SVG file

---

### Visual reference
_PNG examples_

NFT 1
![Image](https://github.com/rmx-party/hacks/assets/71292601/426d86ed-49de-4556-b566-e49491fb9ad1)
NFT 2
![Image](https://github.com/rmx-party/hacks/assets/71292601/b5b89d59-0f23-42d8-bb03-88cd4618ca38)

**Comment by brandondees** [comment]
@paigel opensea metadata format is like this: 
```
{
  "name": "OpenSea Creatures",
  "description": "OpenSea Creatures are adorable aquatic beings primarily for demonstrating what can be done using the OpenSea platform. Adopt one today to try out all the OpenSea buying, selling, and bidding feature set.",
  "image": "external-link-url/image.png",
  "external_link": "external-link-url"
}
```

we can put it on chain easily, just need decisions on what content to fill in. i think specifically, the image here can be another inline SVG. pretty sure this is the square card image, not the banner

**Comment by paigel** [comment]
@brandondees updates on OpenSea metadata: 
* `name` and `description` for OpenSea metadata have been updated in description above ^
* `image` I am working on optimizing size
* all the rest we can leave as-is

**Comment by paigel** [comment]
@brandondees here's optimized svg for OpenSea metadata: 2 optimized versions, one prettified and one not.

- [x] needs review
- [x] needs font style/family adjustment for `monospace`





![Image](https://github.com/rmx-party/hacks/assets/71292601/429e4769-81e7-42ea-b7bf-4035f5e809ab)




[opnses-metadata-rounded-optim.zip](https://github.com/rmx-party/hacks/files/11489901/opnses-metadata-rounded-optim.zip)

**Comment by paigel** [comment]
UPDATE: THIS IS NOW OUT OF DATE; see the next comment

---
@brandondees please update the descriptions for both NFTs and the OpenSea metadata. Swap out the word `signature` for `approval`. To read as follows:


~~The first experiment of our RMXhacks series. Powered by ERC-4337, mint two separate NFTs with one click — no wallet needed, no approval needed. We’re testing for usability, without the frills (pizza bagel included).~~

**Comment by paigel** [comment]
@brandondees per your feedback, please update the descriptions to reflect the below:

```
The first experiment of our RMXhacks series. Powered by ERC-4337, mint two separate NFTs with one click — no seed phrase needed, no approval needed. We’re testing for usability, without the frills (pizza bagel included).
```

**Comment by paigel** [comment]
@brandondees since we are not doing batch transactions, the description can now be:

``` 
The first experiment of our RMXhacks series. Powered by ERC-4337, mint with less friction as we test for usability — no seed phrase or browser extension required.
```

**Comment by brandondees** [comment]
@paigel there's still a chance we can do the batch within Magic. we found some evidence that that might be supported today, it's just not exposed on their ~~marketing~~ documentation site.

**Comment by brandondees** [comment]
but we'll get that updated for the real deploy whichever way it goes

**Comment by paigel** [comment]
> @paigel there's still a chance we can do the batch within Magic. we found some evidence that that might be supported today, it's just not exposed on their ~marketing~ documentation site.

@brandondees that's great to know! let's keep batch transactions as deprioritized and in the icebox for now. If we identify it as an MVP feature in our next scope, we can test it out. tysm

**Comment by brandondees** [comment]
ok i've copied from here to manually add to opensea, lmk if i missed anything @paigel https://testnets.opensea.io/collection/rmxhacks-001

**Comment by paigel** [comment]
looks great @brandondees ! review approved ✅

**Comment by paigel** [comment]
completed ✅
